eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: order
ribbon:
  okhttp:
    enabled: true
#  restclient:
#    enabled: true